### ISSUE TITLE
Module Import Error

### ISSUE THREAD

**Issue by cwotawa** [leBluem/io_import_accsv#1]
Hello !
This is a pretty silly error, but I can't seem to understand where it's coming from. I can't enable the addon because it can't find/import the module import_csv. I don't understand why it doesn't find the module...

This is the traceback error that appears :
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/aurore/Library/Application Support/Blender/2.93/scripts/addons/io_import_accsv-master/__init__.py", line 54, in <module>
    import import_csv
ModuleNotFoundError: No module named 'import_csv'

I've already tried several methods, like using the module importlib in case the problem came from Python, but the error was still there... If anyone has an idea on how to solve this, please share your ideas !
Thanks !

**Comment by febryce** [comment]
Hi, I have the same error. Did you find a solution?

**Comment by realdealgod** [comment]
Hii there, I have the same issue! 
Any fix or workaround?
I couldn't figure out...
Edit: It shows a warning about the version saying 2.9 or above is required, but I'm running 3.1.2.
I saw in the previous releases that version 1.6 had a fix for version check with 3.0. Could this be the problem for version > 3.0? 
Edit2: It might be! Installed version 1.6 and it worked!
